### ISSUE TITLE
[Feature request] Authentication 

### ISSUE THREAD

**Issue by 23rd** [Slipyx/haxebot#1]
Do you plan on making support of authentication using PASS ("server password")?  :3
It would be great.

**Comment by Slipyx** [comment]
I've gone ahead and added a serverPass option to the config file that should be correctly used if it is not empty. I'm not aware of any networks that use a server pass so I couldn't test if it does indeed function. The password will be saved in the config file of course, so be aware of any security concerns that might cause.

**Comment by 23rd** [comment]
Works perfectly!
